export enum LobbyType {
  PublicMatchmaking = 0,
  Practice = 1,
  Tournament = 2,
  Tutorial = 3,
  CoopBots = 4,
  RankedTeamMM = 5,
  RankedSoloMM = 6,
  Ranked = 7,
  OneVsOneMid = 8,
  BattleCup = 9,
  LocalBots = 10,
  Spectator = 11,
  Event = 12,
  Gauntlet = 13,
  NewPlayer = 14,
  Featured = 15,
}
