export enum PermanentBuff {
  MoonShard = 1,
  UltimateScepter = 2,
  SilencerGlaivesOfWisdom = 3,
  PudgeFleshHeap = 4,
  LegionCommanderDuel = 5,
  TomeOfKnowledge = 6,
  LionFingerOfDeath = 7,
  SlarkEssenceShift = 8,
  AbyssalUnderlordAtrophyAura = 9,
  BountyHunterJinada = 10,
  AghanimsShard = 12,
  AxeCullingBlade = 13,
  NecrolyteReapersScythe = 14,
}